name: The Film Dream Initiative
analytics: {}
github: true
description: Communicate. Connect. Collaborate.
author:
  name: 'The Film Dream '
  url: 'http://thefilmdream.com'
  email: thefilmdream@icloud.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/026a1c35-3ad1-4e0a-aac4-80fa501feafe.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/026a1c35-3ad1-4e0a-aac4-80fa501feafe.png
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
layout_spectrum: 0.8638530429452658
color:
  lightness: 0.8516226247538865
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  saturation: 0.8988802486329527
  brandStrength: 0.7585852436624899
  rhythmicContrast: 0.2124200559250126
content_rating:
  adult: false
typography_spectrum: 0.3416490871459246
opengraph: {}
title: The Film Dream Initiative
url: 'http://thefilmdreaminitiative.org'
purpose:
  - type: contact
    url: 'mailto:tfdinitiative@thefilmdream.com'
    label: Email us
  - type: contact
    url: 'tel:+639175260244'
    label: Call us
